CREATE DATABASE ECOM_PLATFORM;
USE ECOM_PLATFORM;

-- ORDER DETAILS (DETAILS ABOUT THE ORDER)
CREATE TABLE OrderDetails (
    OrderDetailID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT,
    ProductID INT,
    Quantity INT,
    Price DECIMAL(10, 2),
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

INSERT INTO OrderDetails (OrderID, ProductID, Quantity, Price) VALUES
(1, 4, 1, 1599.99),
(2, 4, 1, 1599.99),
(3, 1, 1, 99999.99);

